print return value to stderr

diff --git a/docker-run b/docker-run
--- a/docker-run
+++ b/docker-run
@@ -1,9 +1,10 @@
 #!/bin/bash
 
+DIR="$(cd -P "$(dirname "$0")" && pwd)"  # path to directory containing this script
 OS="$(uname -s)" # supported: "Linux", "Darwin" (Mac)
 ARCH="$(uname -m)" # supported: "x86_64", "aarch64" (ARM, Jetson Orin), "arm64" (ARM, Mac)
 
-if ! id -Gn $USER | grep -q "\bdocker\b"; then
+if ! groups | grep -q "\bdocker\b"; then
   echo "User '${USER}' must be in 'docker' group to run containers."
   echo "User can be added via: sudo usermod -aG docker ${USER}"
   echo "Afterwards, the user may need to logout and login again."
@@ -15,6 +16,10 @@ if ! { [[ $OS = "Linux" && $ARCH = "x86_64" ]] || [[ $OS = "Darwin" && $ARCH = "
   exit 1
 fi
 
-CMD=$(python3 generateDockerRunCommand.py "${@}")
+python3 $DIR/generateDockerRunCommand.py "${@}" 2> $DIR/.docker_cmd
+CMD=$(cat $DIR/.docker_cmd)
 echo $CMD
-exec $CMD
+#exec $CMD
+
+# cleanup
+rm -r $DIR/.docker_cmd
